// Mocks generated by Mockito 5.4.6 from annotations
// in atitus_flutter_ui_layer/test/data/repositories/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:atitus_flutter_ui_layer/data/services/api/api_client.dart'
    as _i2;
import 'package:atitus_flutter_ui_layer/data/services/model/available_country.dart'
    as _i5;
import 'package:atitus_flutter_ui_layer/data/services/model/holiday.dart'
    as _i7;
import 'package:atitus_flutter_ui_layer/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [APIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIClient extends _i1.Mock implements _i2.APIClient {
  MockAPIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.AvailableCountry>>> getAvailableCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableCountries, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.AvailableCountry>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.AvailableCountry>>>(
                    this,
                    Invocation.method(#getAvailableCountries, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.AvailableCountry>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.Holiday>>> getHolidays({
    required int? year,
    required String? countryCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHolidays, [], {
              #year: year,
              #countryCode: countryCode,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i7.Holiday>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.Holiday>>>(
                this,
                Invocation.method(#getHolidays, [], {
                  #year: year,
                  #countryCode: countryCode,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.Holiday>>>);
}
